---
- name: Example playbook for gathering system information facts
  hosts: opengear
  gather_facts: false

  tasks:
    - name: Gather system info facts
      opengear.ng.facts:
        gather_network_resources:
          - system_info

    - name: Show system info
      ansible.builtin.debug:
        var: ansible_network_resources.system_info

    - name: Show firmware version
      ansible.builtin.debug:
        msg: "Firmware version: {{ ansible_network_resources.system_info.system_versions.firmware_version }}"

    - name: Show cellular firmware info
      ansible.builtin.debug:
        var: ansible_network_resources.system_info.cellfw_info
      when: ansible_network_resources.system_info.has_cellular
