---
- name: Example playbook for gathering system disk space facts
  hosts: opengear
  gather_facts: false

  tasks:
    - name: Gather disk space facts
      opengear.ng.facts:
        gather_network_resources:
          - system_diskspace

    - name: Set system diskspace fact
      ansible.builtin.set_fact:
        system_diskspace: "{{ ansible_facts['network_resources']['system_diskspace'] }}"

    - name: Show disk space for all mounts
      ansible.builtin.debug:
        var: system_diskspace
